In [19]:
%pip install transformers[ja,sentencepiece,torch]==4.30 pandas

Collecting transformers==4.30 (from transformers[ja,sentencepiece,torch]==4.30)
  Using cached transformers-4.30.0-py3-none-any.whl.metadata (113 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (3.25.2)
Collecting huggingface-hub<1.0,>=0.14.1 (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2.32.4)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30)
  Using cached tokenizers-0.13.3.tar.gz (314 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (4.67.3)
Requirement already satisfied: fugashi>=1.0 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.5.2)
Requirement already satisfied: ipadic<2.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.0.0)
Requirement already satisfied: unidic-lite>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.0.8)
Requirement already satisfied: unidic>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.1.0)
Requirement already satisfied: sudachipy>=0.6.6 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (0.6.11)
Requirement already satisfied: sudachidict-core>=20220729 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (20260116)
Requirement already satisfied: rhoknp<1.3.1,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.3.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (0.2.1)
Collecting protobuf<=3.20.3 (from transformers[ja,sentencepiece,torch]==4.30)
  Using cached protobuf-3.20.3-py2.py3-none-any.whl.metadata (720 bytes)
Requirement already satisfied: torch!=1.12.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (2.10.0+cpu)
Requirement already satisfied: accelerate>=0.20.2 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,sentencepiece,torch]==4.30) (1.13.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.20.2->transformers[ja,sentencepiece,torch]==4.30) (5.9.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (3.1.6)
Requirement already satisfied: wasabi<1.0.0,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from unidic>=1.0.2->transformers[ja,sentencepiece,torch]==4.30) (0.10.1)
Requirement already satisfied: plac<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from unidic>=1.0.2->transformers[ja,sentencepiece,torch]==4.30) (1.4.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.30->transformers[ja,sentencepiece,torch]==4.30) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch!=1.12.0,>=1.9->transformers[ja,sentencepiece,torch]==4.30) (3.0.3)
Using cached transformers-4.30.0-py3-none-any.whl (7.2 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached protobuf-3.20.3-py2.py3-none-any.whl (162 kB)
Building wheels for collected packages: tokenizers
  error: subprocess-exited-with-error

  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for tokenizers (pyproject.toml) ... error
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tokenizers)

In [20]:
from transformers import pipeline

In [21]:
generater = pipeline(
    "text-generation", 
    model = "abeja/gpt2-large-japanese"
)
# "日本で一番高い山は"に続くテキストを生成
outputs = generater("日本で一番高い山は")
print(outputs[0]["generated_text"])

Loading weights:   0%|          | 0/437 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: abeja/gpt2-large-japanese
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...35}.attn.bias        | UNEXPECTED |  |
transformer.h.{0...35}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

日本で一番高い山は富士山 ではなく 標高3,876mの 霊仙山 である。 しかし、霊仙山は 霊山 (りょうぜんざん) ではなく 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山の東にある 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山 (りょうせんざん) であり、霊仙山の西にある 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山 (りょうせんざん) であるが、霊仙山の東にある 霊仙山 (りょうせんざん) が 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山 (りょうせんざん) であるが、霊仙山の西にある 霊仙山 (りょうせんざん) が 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山 (りょうせんざん) であるが、霊仙山の西にある 霊仙山 (りょうせんざん) が 霊仙山 (りょうせんざん) である。 霊仙山は 霊仙山 (りょうせんざん) であり、霊

In [22]:
import pandas as pd

fill_mask = pipeline(
    "fill-mask",
    model = "cl-tohoku/bert-base-japanese-v3"
)
masked_text = "日本の首都は[MASK] である"
outputs = fill_mask(masked_text)
display(pd.DataFrame(outputs[:3]))

Loading weights:   0%|          | 0/204 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertForMaskedLM LOAD REPORT from: cl-tohoku/bert-base-japanese-v3
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.pooler.dense.bias       | UNEXPECTED |  |
bert.embeddings.position_ids | UNEXPECTED |  |
cls.seq_relationship.bias    | UNEXPECTED |  |
cls.seq_relationship.weight  | UNEXPECTED |  |
bert.pooler.dense.weight     | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

      score  token token_str           sequence
0  0.884170  12569        東京  日本 の 首都 は 東京 で ある
1  0.024820  12759        大阪  日本 の 首都 は 大阪 で ある
2  0.020864  13017        京都  日本 の 首都 は 京都 で ある

In [23]:
masked_text = "今日の映画は刺激的で楽しかった。この映画は [MASK] 。"
outputs = fill_mask(masked_text)
display(pd.DataFrame(outputs[:3]))

      score  token token_str                                   sequence
0  0.729103  23845     素晴らしい  今日 の 映画 は 刺激 的 で 楽しかっ た 。 この 映画 は 素晴らしい 。
1  0.067442  26840       楽しい    今日 の 映画 は 刺激 的 で 楽しかっ た 。 この 映画 は 楽しい 。
2  0.063454  24683       面白い    今日 の 映画 は 刺激 的 で 楽しかっ た 。 この 映画 は 面白い 。

In [24]:
t2t_generater = pipeline(
    "text2text-generation",
    model = "retrieva-jp/t5-large-long"
)
masked_text = "江戸幕府を開いたのは、<extra_id_0> である"
outputs = t2t_generater(masked_text, eos_token_id=32098)
print(outputs[0]["generated_text"])

KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'image-to-image', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'question-answering', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'visual-question-answering', 'vqa', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection', 'translation_XX_to_YY']"

In [25]:
"日本銀行" in t2t_generater.tokenizer.vocab

NameError: name 't2t_generater' is not defined